from AMSpi import AMSpi

CONVEYOR_MOTOR = AMSpi.DC_Motor_1
PUSHER_MOTOR = AMSpi.DC_Motor_2

#Pin for motion sensor
MOTION_SENSOR_PIN = 17

CONVEYOR_SPEED = 70
PUSHER_SPEED = 70
PUSHER_TIME = 2
CONVEYOR_TIME = 2


# Color sensor pins
COLOR_SENSOR_PIN_1 = 2
COLOR_SENSOR_PIN_2 = 3
COLOR_SENSOR_PIN_3 = 23
COLOR_SENSOR_PIN_4 = 24
SIGNAL_SENSOR_PIN = 25

#Pins for shift register 
LATCH_REGISTER_PIN = 21
CLK_REGISTER_PIN = 20
SER_REGISTER_PIN = 16

#Pins for motors on Arduino
MOTOR_1_PIN = 5
MOTOR_2_PIN = 6
MOTOR_3_PIN = 13
MOTOR_4_PIN = 19


